theme: jekyll-theme-slate
title: Kirill Markin | founder ozma.io | contacts, media
description: Contacts and related URLs to Kirill Markin. Social media profiles, instagram, Linkedin, email and phone.
email: markinkirill@gmail.com
url: "https://kirill-markin.com"
twitter_username: kirill_markin_
github:
  is_project_page: false
gtm: GTM-NJZKH2L
