theme: jekyll-theme-slate
title: Kirill Markin | founder ozma.io | contacts, media
description: Contacts and related URLs to Kirill Markin. Social media profiles, instagram, Linkedin, email and phone.
github:
  is_project_page: false